//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Bankaccount')
export class BankaccountEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  bankName: string;

  @Column('text', { nullable: true })
  accountNumber: string;
}
