//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Expense')
export class ExpenseEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('real', { nullable: true })
  amount: number;

  @Column('date', { nullable: true })
  date: Date;

  @Column('text', { nullable: true })
  description: string;

  @Column('integer', { nullable: true })
  categoryId: number;

  @Column('integer', { nullable: true })
  bankAccountId: number;
}
