//Source code generated by AppGPT (www.appgpt.tech)
//to be autogenerated as template, one per resource
import { Entity, Column, PrimaryGeneratedColumn } from 'typeorm';

@Entity('Smsmessage')
export class SmsmessageEntity {
  @PrimaryGeneratedColumn()
  id: number;

  @Column('text', { nullable: true })
  sender: string;

  @Column('text', { nullable: true })
  messageBody: string;

  @Column('date', { nullable: true })
  receivedAt: Date;

  @Column('bool', { nullable: true })
  processed: boolean;
}
